# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dsid.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dsid.proto',
  package='dsidRpc',
  syntax='proto3',
  serialized_pb=_b('\n\ndsid.proto\x12\x07\x64sidRpc\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"$\n\x0blongRequest\x12\x15\n\rnumberRequest\x18\x01 \x01(\x03\" \n\tlongReply\x12\x13\n\x0bnumberReply\x18\x01 \x01(\x03\"(\n\x10\x65ightLongRequest\x12\x14\n\x0c\x61rrayRequest\x18\x01 \x03(\x03\"$\n\x0e\x65ightLongReply\x12\x12\n\narrayReply\x18\x01 \x03(\x03\"$\n\rstringRequest\x12\x13\n\x0bnameRequest\x18\x01 \x01(\t\" \n\x0bstringReply\x12\x11\n\tnameReply\x18\x01 \x01(\t\"&\n\x0e\x63omplexRequest\x12\x14\n\x0c\x61lunoRequest\x18\x01 \x01(\x0c\"\"\n\x0c\x63omplexReply\x12\x12\n\nalunoReply\x18\x01 \x01(\x0c\x32\xb2\x02\n\x04\x44sid\x12,\n\x08voidCall\x12\x0e.dsidRpc.Empty\x1a\x0e.dsidRpc.Empty\"\x00\x12\x36\n\x08longCall\x12\x14.dsidRpc.longRequest\x1a\x12.dsidRpc.longReply\"\x00\x12\x45\n\reightLongCall\x12\x19.dsidRpc.eightLongRequest\x1a\x17.dsidRpc.eightLongReply\"\x00\x12<\n\nstringCall\x12\x16.dsidRpc.stringRequest\x1a\x14.dsidRpc.stringReply\"\x00\x12?\n\x0b\x63omplexCall\x12\x17.dsidRpc.complexRequest\x1a\x15.dsidRpc.complexReply\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='dsidRpc.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='dsidRpc.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=51,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='dsidRpc.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='dsidRpc.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=82,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='dsidRpc.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=91,
)


_LONGREQUEST = _descriptor.Descriptor(
  name='longRequest',
  full_name='dsidRpc.longRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numberRequest', full_name='dsidRpc.longRequest.numberRequest', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=129,
)


_LONGREPLY = _descriptor.Descriptor(
  name='longReply',
  full_name='dsidRpc.longReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numberReply', full_name='dsidRpc.longReply.numberReply', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=163,
)


_EIGHTLONGREQUEST = _descriptor.Descriptor(
  name='eightLongRequest',
  full_name='dsidRpc.eightLongRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='arrayRequest', full_name='dsidRpc.eightLongRequest.arrayRequest', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=205,
)


_EIGHTLONGREPLY = _descriptor.Descriptor(
  name='eightLongReply',
  full_name='dsidRpc.eightLongReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='arrayReply', full_name='dsidRpc.eightLongReply.arrayReply', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=243,
)


_STRINGREQUEST = _descriptor.Descriptor(
  name='stringRequest',
  full_name='dsidRpc.stringRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nameRequest', full_name='dsidRpc.stringRequest.nameRequest', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=281,
)


_STRINGREPLY = _descriptor.Descriptor(
  name='stringReply',
  full_name='dsidRpc.stringReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nameReply', full_name='dsidRpc.stringReply.nameReply', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=315,
)


_COMPLEXREQUEST = _descriptor.Descriptor(
  name='complexRequest',
  full_name='dsidRpc.complexRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='alunoRequest', full_name='dsidRpc.complexRequest.alunoRequest', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=355,
)


_COMPLEXREPLY = _descriptor.Descriptor(
  name='complexReply',
  full_name='dsidRpc.complexReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='alunoReply', full_name='dsidRpc.complexReply.alunoReply', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=357,
  serialized_end=391,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['longRequest'] = _LONGREQUEST
DESCRIPTOR.message_types_by_name['longReply'] = _LONGREPLY
DESCRIPTOR.message_types_by_name['eightLongRequest'] = _EIGHTLONGREQUEST
DESCRIPTOR.message_types_by_name['eightLongReply'] = _EIGHTLONGREPLY
DESCRIPTOR.message_types_by_name['stringRequest'] = _STRINGREQUEST
DESCRIPTOR.message_types_by_name['stringReply'] = _STRINGREPLY
DESCRIPTOR.message_types_by_name['complexRequest'] = _COMPLEXREQUEST
DESCRIPTOR.message_types_by_name['complexReply'] = _COMPLEXREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREQUEST,
  __module__ = 'dsid_pb2'
  # @@protoc_insertion_point(class_scope:dsidRpc.HelloRequest)
  ))
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREPLY,
  __module__ = 'dsid_pb2'
  # @@protoc_insertion_point(class_scope:dsidRpc.HelloReply)
  ))
_sym_db.RegisterMessage(HelloReply)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'dsid_pb2'
  # @@protoc_insertion_point(class_scope:dsidRpc.Empty)
  ))
_sym_db.RegisterMessage(Empty)

longRequest = _reflection.GeneratedProtocolMessageType('longRequest', (_message.Message,), dict(
  DESCRIPTOR = _LONGREQUEST,
  __module__ = 'dsid_pb2'
  # @@protoc_insertion_point(class_scope:dsidRpc.longRequest)
  ))
_sym_db.RegisterMessage(longRequest)

longReply = _reflection.GeneratedProtocolMessageType('longReply', (_message.Message,), dict(
  DESCRIPTOR = _LONGREPLY,
  __module__ = 'dsid_pb2'
  # @@protoc_insertion_point(class_scope:dsidRpc.longReply)
  ))
_sym_db.RegisterMessage(longReply)

eightLongRequest = _reflection.GeneratedProtocolMessageType('eightLongRequest', (_message.Message,), dict(
  DESCRIPTOR = _EIGHTLONGREQUEST,
  __module__ = 'dsid_pb2'
  # @@protoc_insertion_point(class_scope:dsidRpc.eightLongRequest)
  ))
_sym_db.RegisterMessage(eightLongRequest)

eightLongReply = _reflection.GeneratedProtocolMessageType('eightLongReply', (_message.Message,), dict(
  DESCRIPTOR = _EIGHTLONGREPLY,
  __module__ = 'dsid_pb2'
  # @@protoc_insertion_point(class_scope:dsidRpc.eightLongReply)
  ))
_sym_db.RegisterMessage(eightLongReply)

stringRequest = _reflection.GeneratedProtocolMessageType('stringRequest', (_message.Message,), dict(
  DESCRIPTOR = _STRINGREQUEST,
  __module__ = 'dsid_pb2'
  # @@protoc_insertion_point(class_scope:dsidRpc.stringRequest)
  ))
_sym_db.RegisterMessage(stringRequest)

stringReply = _reflection.GeneratedProtocolMessageType('stringReply', (_message.Message,), dict(
  DESCRIPTOR = _STRINGREPLY,
  __module__ = 'dsid_pb2'
  # @@protoc_insertion_point(class_scope:dsidRpc.stringReply)
  ))
_sym_db.RegisterMessage(stringReply)

complexRequest = _reflection.GeneratedProtocolMessageType('complexRequest', (_message.Message,), dict(
  DESCRIPTOR = _COMPLEXREQUEST,
  __module__ = 'dsid_pb2'
  # @@protoc_insertion_point(class_scope:dsidRpc.complexRequest)
  ))
_sym_db.RegisterMessage(complexRequest)

complexReply = _reflection.GeneratedProtocolMessageType('complexReply', (_message.Message,), dict(
  DESCRIPTOR = _COMPLEXREPLY,
  __module__ = 'dsid_pb2'
  # @@protoc_insertion_point(class_scope:dsidRpc.complexReply)
  ))
_sym_db.RegisterMessage(complexReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'))

_DSID = _descriptor.ServiceDescriptor(
  name='Dsid',
  full_name='dsidRpc.Dsid',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=394,
  serialized_end=700,
  methods=[
  _descriptor.MethodDescriptor(
    name='voidCall',
    full_name='dsidRpc.Dsid.voidCall',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='longCall',
    full_name='dsidRpc.Dsid.longCall',
    index=1,
    containing_service=None,
    input_type=_LONGREQUEST,
    output_type=_LONGREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='eightLongCall',
    full_name='dsidRpc.Dsid.eightLongCall',
    index=2,
    containing_service=None,
    input_type=_EIGHTLONGREQUEST,
    output_type=_EIGHTLONGREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='stringCall',
    full_name='dsidRpc.Dsid.stringCall',
    index=3,
    containing_service=None,
    input_type=_STRINGREQUEST,
    output_type=_STRINGREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='complexCall',
    full_name='dsidRpc.Dsid.complexCall',
    index=4,
    containing_service=None,
    input_type=_COMPLEXREQUEST,
    output_type=_COMPLEXREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DSID)

DESCRIPTOR.services_by_name['Dsid'] = _DSID

# @@protoc_insertion_point(module_scope)
